# Site settings
title: Hello Octopress 3.0
email: samar.panda84@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Demostrating the use of Octopress 3.0 for blogging. It's an obsessively designed toolkit for writing and deploying [Jekyll](http://jekyllrb.com/) blogs.
baseurl: "/hello_octopress_3" # the subpath of your site, e.g. /blog/
url: "http://samarpanda.com" # the base hostname & protocol for your site
twitter_username: samarpanda
github_username:  samarpanda

# Build settings
markdown: redcarpet
highlighter: pygments

gems:
  - octopress-codeblock
  - octopress-codefence
  - octopress-solarized

exclude:
  - .code-highlighter-cache
